server:
  port: 8080

service:
  #helloHost: localhost
  helloHost: ${HELLO_SERVICE_HOST}

# new

opentracing:
  jaeger:
    http-sender:
      #url: http://localhost:14268/api/traces
      url: http://${JAEGER_HOST}:14268/api/traces
    #enable-b3-propagation: true
spring:
  application:
    name: greetings-service