server:
  port: 8888

service:
  messageHost: ${MESSAGE_SERVICE_HOST}
  messagePort: ${MESSAGE_SERVICE_PORT}
  nameHost: ${NAME_SERVICE_HOST}
  namePort: ${NAME_SERVICE_PORT}

spring:
  application:
    name: hello-service