server:
  port: 8080

service:
  helloHost: ${HELLO_SERVICE_HOST}
  helloPort: ${HELLO_SERVICE_PORT}
  fortuneHost: ${FORTUNE_SERVICE_HOST}
  fortunePort: ${FORTUNE_SERVICE_PORT}

spring:
  application:
    name: greetings-service